
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: iddqdidkfa
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: school_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
